In [5]:
opt = {1:{'mu':0,'siguma':100},2:{'mu':0,'siguma':100}}
print(opt[1]['mu'])

0


In [1]:
#必要なモジュールのインポート
import pandas as pd
import numpy as np
import pydotplus
import matplotlib.pyplot as plt
  
def markovViz(markovdf, fileName='default.png'):
     
    #オブジェクトを定義
    graph = pydotplus.Dot(graph_type='digraph')
     
    #ノードを追加
    for c in df.columns:
        node = pydotplus.Node(c)
        graph.add_node(node)
     
    #エッジを追加    
    for i in df.index:
        for c in df.columns:
            if df.ix[i, c] > 0:
                edge = pydotplus.Edge(graph.get_node(i)[0], graph.get_node(c)[0])
                edge.set_label('{:.1f}'.format(df.ix[i, c]))
                graph.add_edge(edge)
 
    #グラフ描画                
    graph.write_png(fileName, prog='dot')
    


if __name__ == "__main__":    
    df = pd.DataFrame(index=['a', 'b', 'c', 'd'],
                      columns=['a', 'b', 'c', 'd'], 
                      data=[[0.6, 0.2, 0.2, 0.0],
                            [0.7, 0.3, 0.0, 0.0],
                            [0.0, 0.4, 0.5, 0.1],
                            [0.1, 0.3, 0.3, 0.3]])
     
    markovViz(df)

C:\Users\okdmlab\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\okdmlab\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated


InvocationException: GraphViz's executables not found

In [5]:
import numpy as np
import pydotplus
 
def neuralViz(shape, fileName='default.png', plot=True, Wlist=None):
      
    #形状をnp配列に変換
    args = np.array(shape)
      
    #空のmatrixを作成（adjacency_matrix作成用）
    matrix = np.zeros((args.sum(), args.sum()))
     
    #結合の強さに関するmatrixを取得したいときに使います。（本記事では未使用）
    if Wlist is not None:
        wmatrix = np.zeros((args.sum(), args.sum())) 
      
    #結ぶノード間に１を入力
    for i in range(len(args)-1):
        tmp1 = args[:i+1].sum()
        tmp0 = args[:i].sum()
        matrix[tmp1:tmp1+args[i+1],tmp0:tmp0+args[i]] = 1  
               
        if  Wlist is not None:
            wmatrix[tmp1:tmp1+args[i+1],tmp0:tmp0+args[i]] = Wlist[i].data
      
    #GraphVizの機能を使って描画
    g=pydotplus.graph_from_adjacency_matrix(matrix.T.tolist(), node_prefix=0)
  
    #何もしないとNodeが作られないので足す。ついでに文字を消す。
    for i in range(args.sum()):
        n = pydotplus.Node(i+1)
        n.set_fontsize(0)
        g.add_node(n)
     
    if plot == True:
        #グラフ書き出し（'default.png'）    
        g.write_png(fileName, prog='dot')
         
    else:
        return g, matrix.T, wmatrix.T 
neuralViz([3, 4, 6, 3, 2, 5])

InvocationException: GraphViz's executables not found

In [14]:
import numpy as np

INIT_STATE = 0

PROB_MATRIX = [[0.7, 0.1, 0.2],
               [0.2, 0.1, 0.7],
               [0.7, 0.2, 0.1]]

def get_next_state(prob_array):
    #print('prob_array',prob_array)
    normalization_factor = sum(prob_array)
    #print('normalization_factor',normalization_factor)
    rand_num = np.random.rand(1)
    #print('rand_num',rand_num)
    s = 0
    for i in range(len(prob_array)):
        s += prob_array[i]/normalization_factor
        #print('s',s)
        if rand_num < s:
            return i
    return -1

if __name__ == "__main__":
    print("Initial State: " + str(INIT_STATE))
    cur_state = INIT_STATE
    for i in range(2):
        cur_state = get_next_state(PROB_MATRIX[cur_state])
        print("State" + str(i+1) + " : " + str(cur_state))

Initial State: 0
State1 : 0
State2 : 0


In [4]:
import numpy as np
#晴の日の翌日が、晴になる確率は 0.6 曇りになる確率は 0.3 雨になる確率は 0.1
#曇の日の翌日が、晴になる確率は 0.3 曇りになる確率は 0.6 雨になる確率は 0.1
#雨の日の翌日が、晴になる確率は 0.2 曇りになる確率は 0.3 雨になる確率は 0.5
#これを行列で表すと
prob_matrix  =np.array(
[[0.6, 0.3, 0.1],
[0.3, 0.6, 0.1],
[0.2, 0.3, 0.5]])

#初期状態を、晴として、翌日の天気の確率分布を計算（10日後まで繰り返す）
state = np.array([1,0, 0])
for x in range(10):
    state = np.dot(state,prob_matrix)
    print('{0}日後'.format(x + 1))
    print(state)

1日後
[0.6 0.3 0.1]
2日後
[0.47 0.39 0.14]
3日後
[0.427 0.417 0.156]
4日後
[0.4125 0.4251 0.1624]
5日後
[0.40751 0.42753 0.16496]
6日後
[0.405757 0.428259 0.165984]
7日後
[0.4051287 0.4284777 0.1663936]
8日後
[0.40489925 0.42854331 0.16655744]
9日後
[0.40481403 0.42856299 0.16662298]
10日後
[0.40478191 0.4285689  0.16664919]


In [4]:
from input_sensor import Input
from test1 import Times1

CG = Input()
CG.load()
time_1 = Times1(CG.load)

AttributeError: 'function' object has no attribute 'x'